routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cities', 'CityController');
Route::resource('barangays', 'BarangayController');
Route::resource('patients', 'PatientController');
Route::get('/patient-checkstatus', 'CheckStatusController@index');
Route::get('/awareness-report', 'AwarenessReportsController@index');
Route::get('/coronavirus-report', 'CoronaVirusReportsController@index');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class City extends Model
{
    // The attributes that are mass assignable
    protected $fillable = [
    'name'
    ];

    // Relationship many barangays to one city
    public function barangays(){
        return $this->HasMany(Barangay::class);
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\City;

class CityController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */

    /** Authentication for pages **/
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    } 

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        /**  Retrieve all cities **/
        $cities = City::orderBy('name', 'asc')->paginate(10);
        return view('cities.index')->with('cities', $cities);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /**  Create new city **/
        return view('cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /** Form Validation **/
        $request->validate([
            'name'=>'required'
        ]);

        /** Create City **/
        $city = new City;
        $city->name = $request->input('name');
        $city->save();
        return redirect('/cities')->with('success', 'City saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /** Show city information **/
        $city = City::find($id);
        return view('cities.show')->with('city', $city);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        /**  Edit city **/
        $city = City::find($id);
        return view('cities.edit')->with('city', $city);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**  Form validation **/
        $request->validate([
            'name'=>'required'
        ]);

        /**  Update city information **/
        $city= City::find($id);
        $city->name =  $request->get('name');
        $city->save();
        return redirect('/cities')->with('success', 'City Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        /**  Delete a city **/
        $city= City::find($id);
        $city->delete();
        return redirect('/cities')->with('success', 'City Deleted!');
    }
}

resources/views/cities/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-4 mb-2">
 <div class="col-sm-8 offset-sm-2">
    <h1>Add a City</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('cities.store') }}">
          @csrf
          <div class="form-group">    
              <label for="first_name">Name:</label>
              <input type="text" class="form-control" name="name" placeholder="Enter name of city"/>
          </div>                       
          <button type="submit" class="btn btn-success">Add</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/cities/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-4 mb-2">
    <div class="col-sm-8 offset-sm-2">
        <h1>Update City</h1>
    </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="/cities/{{ $city->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name <span class="required">*</span></label>
                    <input type="text" name="name" value="{{ $city->name }}" class="form-control" id="name" placeholder="Enter name of city">
                </div>
                <button type="submit" class="btn btn-primary">Update</button> <a href="/cities" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
@endsection

resources/views/cities/index.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
<div class="col-sm-8 offset-sm-2">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
<div class="row mt-4 mb-2">
<div class="col-sm-8 offset-sm-2">
    <div class="row">
        <div class="col-sm-6">
            <h1>City</h1>
        </div>
        <div class="col-sm-6">
            <a href="/cities/create" class="btn btn-warning pull-right float-right">Add City</a>
        </div>
    </div>
    @if(count($cities) > 0)
        <table class="table table-striped">
    <thead>
        <tr>
          <th>Name</th>
          <th colspan = 2>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($cities as $city)
        <tr>
            <td>{{$city->name}}</td>
            <td>
                    <a href="cities/{{$city->id}}" class="btn btn-primary float-left mr-2">View</a>
                    <a href="/cities/{{$city->id}}/edit" class="btn btn-success float-left mr-2"><i class="fa fa-edit"></i>Edit</a>
                    <form action="/cities/{{$city->id}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit" onclick="return confirm(`Are you sure you want to delete city '{{ $city->name }}'?`);">Delete</button>
                    </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
        {{$cities->links()}}
    @else
        <p>No city found</p>
    @endif
    <div>
</div>
@endsection

resources/views/cities/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-4 mb-2">
        <div class="col-sm-6 offset-sm-2">
            <h1 >City Information</h1>
        </div>
        <div class="col-sm-2">
            <a href="/cities" class="btn btn-success pull-right float-right">Go back</a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <table class="table table-striped">
                <tr>
                    <th>City</th>
                    
                </tr>
                <tr>
                    <td>{{ $city->name }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection