routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cities', 'CityController');
Route::resource('barangays', 'BarangayController');
Route::resource('patients', 'PatientController');
Route::get('/patient-checkstatus', 'CheckStatusController@index');
Route::get('/awareness-report', 'AwarenessReportsController@index');
Route::get('/coronavirus-report', 'CoronaVirusReportsController@index');

app/Patient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    // The attributes that are mass assignable
    protected $fillable = [
        'name',
        'barangay_id',
        'name',
        'number',
        'email',
        'case_type',
        'coronavirus_status'
    ];
    
    // Relationship barangay to patients
    public function barangay(){
        return $this->belongsTo(Barangay::class);
    }

}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Patient;
use App\Barangay;
use App\City;
use App\Mail\CaseTypeChangeMail;
use Illuminate\Support\Facades\Mail;


class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    /** Authentication for pages **/
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }
    
    public function index()
    {
        /**  Retrieve all patients **/
        $patients = Patient::orderBy('name', 'asc')->paginate(10);
        $barangays = Barangay::all();
        $cities = City::all();
        return view('patients.index')->with(['patients' => $patients, 'barangays' => $barangays, 'cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /**  Create new patient **/
        $barangays = Barangay::all();
        $cities = City::all();
        $case_types = ["PUI", "PUM", "Positive", "Negative"];
        $status_list = ["Active", "Recovered", "Deceased"];
        return view('patients.create')->with([
            'barangays' => $barangays,
            'cities' => $cities,
            'case_types' => $case_types, 
            'status_list' => $status_list
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $patient = new Patient;

        /** Form Validation **/
        $this->validate($request, [
            'name' => 'required',
            'city' => 'required',
            'barangay' => 'required',
            'number' => 'required',
            'email' => "nullable|email|unique:patients,email,{$patient->id}",
            'case_type' => 'required'
        ]);
        
        /** Create Patient **/
        $patient->name = $request->input('name');
        $patient->barangay_id = $request->input('barangay');
        $patient->number = $request->input('number');
        $patient->email = $request->input('email');
        $patient->case_type = $request->input('case_type');
        $patient->coronavirus_status = $request->input('coronavirus_status');
        $patient->save();

        return redirect('/patients')->with('success', 'Patient Saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /** Show patient information **/
         $patient = Patient::find($id);
         $barangay = Patient::find($id)->barangay;
         $barangay_id = Patient::find($id)->barangay_id;
         $city = Barangay::find($barangay_id)->city;
 
         return view('patients.show')->with(['patient' => $patient, 'barangay' => $barangay, 'city' => $city]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         /**  Edit patient **/
         $patient = Patient::find($id);
         $barangays = Barangay::all();
         $cities = City::all();
         $case_types = ["PUI", "PUM", "Positive", "Negative"];
         $status_list = ["Active", "Recovered", "Deceased"];
 
         return view('patients.edit')->with([
             'patient' => $patient, 
             'barangays' => $barangays, 
             'cities' => $cities, 
             'case_types' => $case_types,
             'status_list' => $status_list
         ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**  Form validation **/
        $this->validate($request, [
            'name' => 'required',
            'city' => 'required',
            'barangay' => 'required',
            'number' => 'required',
            'email' => "nullable|email|unique:patients,email,{$id}",
            'case_type' => 'required'
        ]);

        /**  Update patient information **/
        $patient = Patient::find($id);
        $patient->name = $request->input('name');
        $patient->barangay_id = $request->input('barangay');
        $patient->number = $request->input('number');
        $patient->email = $request->input('email');
        $patient->case_type = $request->input('case_type');
        $patient->coronavirus_status = $request->input('covid_status');

        /* Send email notification user change case type of patient*/
        if($patient->isDirty('case_type')){
            Mail::to($patient->email)->send(new CaseTypeChangeMail($patient->case_type, $patient->name));
        }
        
        $patient->save();
        return redirect('/patients')->with('success', 'Patient Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        /**  Delete a patient **/
        $patient= Patient::find($id);
        $patient->delete();
        return redirect('/patients')->with('success', 'Patient Deleted!');
    }
}

resources/views/patients/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-4 mb-2">
        <div class="col-sm-8 offset-sm-2">
            <h1>Add New Patient</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
        @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
             <form method="post" action="{{ route('patients.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">Name <span class="required">*</span></label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Enter name of patient">
                </div>
                <div class="form-group">
                    <label for="barangay">City <span class="required">*</span></label>
                    <select class="form-control" id="select-city" name="city">
                        <option value="">Select City</option>
                        @foreach ($cities as $city)
                            <option value="{{ $city->id }}">{{ $city->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="barangay">Barangay</label>
                     <select class="form-control" id="select-barangay" name="barangay">
                        <option value="">Select Barangay</option>
                        @foreach ($barangays as $barangay)
                            <option city-data-id="{{$barangay->city_id}}" value="{{ $barangay->id }}">{{ $barangay->name }}</option>
                        @endforeach
                    </select> 
                </div>
                <div class="form-group">
                    <label for="number">Contact No. <span class="required">*</span></label>
                    <input type="text" name="number" class="form-control" id="number" placeholder="Mobile / Tel. / Phone">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" id="email" placeholder="Enter your Email">
                </div>
                <div class="form-group">
                    <label for="case-type">Case Type <span class="required">*</span></label>
                    <select class="form-control" id="case-type" name="case_type">
                        <option value="">Select Case Type</option>
                        @foreach ($case_types as $case_type)
                            <option value="{{$case_type}}">{{$case_type}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group hidden">
                    <label for="coronavirus-status">Corona Virus Status <span class="required">*</span></label>
                    <select class="form-control" id="coronavirus-status" name="coronavirus_status">
                        <option value="">Select Status</option>
                        @foreach ($status_list as $status)
                            <option value="{{$status}}">{{$status}}</option>
                        @endforeach
                    </select>
                </div>
                <input class="btn btn-primary" type="submit" value="Add"> <a href="/patients" class="btn btn-light">Cancel</a>
            </form>       
        </div>
    </div>
@endsection

resources/views/patients/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-4 mb-2">
        <div class="col-sm-8 offset-sm-2">
            <h1>Update Patient</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="/patients/{{ $patient->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name <span class="required">*</span></label>
                    <input type="text" name="name" value="{{ $patient->name }}" class="form-control" id="name" placeholder="Enter name of patient">
                </div>
                <div class="form-group">
                    <label for="barangay">City <span class="required">*</span></label>
                    <select class="form-control" id="select-city" name="city">
                        <option value="">Select City</option>
                        @foreach ($barangays as $barangay)
                            @if ($barangay->id == $patient->barangay_id)
                                @foreach ($cities as $city)
                                    @if ($barangay->city_id == $city->id)
                                        <option value="{{ $city->id }}" selected="selected">{{ $city->name }}</option>
                                    @else
                                        <option value="{{ $city->id }}">{{ $city->name }}</option>
                                    @endif
                                @endforeach
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="barangay">Barangay</label>
                    <select class="form-control" id="select-barangay" name="barangay">
                        <option value="">Select Barangay</option>
                        @foreach ($barangays as $barangay)
                            @if ($barangay->id == $patient->barangay_id)
                                <option city-data-id="{{$barangay->city_id}}" value="{{ $barangay->id }}" selected="selected">{{ $barangay->name }}</option>
                            @else
                                <option city-data-id="{{$barangay->city_id}}" value="{{ $barangay->id }}">{{ $barangay->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="number">Contact No. <span class="required">*</span></label>
                    <input type="text" name="number" value="{{ $patient->number }}" class="form-control" id="number" placeholder="Mobile / Tel. / Phone">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" value="{{ $patient->email }}" class="form-control" id="email" placeholder="Enter your Email">
                </div>
                <div class="form-group">
                    <label for="case-type">Case Type <span class="required">*</span></label>
                    <select class="form-control" id="case-type" name="case_type">
                        <option value="">Select Case Type</option>
                        @foreach ($case_types as $case_type)
                            @if ($patient->case_type == $case_type)
                                <option value="{{$case_type}}" selected="selected">{{$case_type}}</option>
                            @else
                                <option value="{{$case_type}}">{{$case_type}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <div class="form-group hidden-field">
                    <label for="covid-status">Corono Virus Status <span class="required">*</span></label>
                    <select class="form-control" id="covid-status" name="covid_status">
                        <option value="">Select Status</option>
                        @foreach ($status_list as $status)
                            @if ($patient->covid_status == $status)
                                <option value="{{$status}}" selected="selected">{{$status}}</option>
                            @else
                                <option value="{{$status}}">{{$status}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <input class="btn btn-primary" type="submit" value="Update"> <a href="/patients" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
@endsection

resources/views/patients/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-4 mb-2">
    
<div class="col-sm-8 offset-sm-2">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
<div class="row">
    
<div class="col-sm-8 offset-sm-2">
    <div class="row">
        <div class="col-sm-6">
            <h1>Patient</h1>
        </div>
        <div class="col-sm-6">
            <a href="/patients/create" class="btn btn-warning pull-right float-right">Add Patient</a>
        </div>
    </div>
    @if(count($patients) > 0)
        <table class="table table-striped">
    <thead>
        <tr>
          <th>Name</th>
          <th>City</th>
          <th>Brgy</th>
          <th>Case Type</th>
          <th>Actions</th>
        </tr>
    </thead>
    <tbody>
      @foreach ($patients as $patient)
                            <tr>
                                <td>{{$patient->name}}</td>
                                @foreach ($barangays as $barangay)
                                    @if ($barangay->id == $patient->barangay_id)
                                        @foreach ($cities as $city)
                                            @if ($barangay->city_id == $city->id)
                                                <td>{{$city->name}}</td>
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                                @foreach ($barangays as $barangay)
                                    @if ($barangay->id == $patient->barangay_id)
                                        <td>{{$barangay->name}}</td>
                                    @endif
                                @endforeach
                                <td>{{$patient->case_type}}</td>
                                <td>
                                    <a href="/patients/{{$patient->id}}" class="btn btn-primary float-left mr-2">View</a>
                                    <a href="/patients/{{$patient->id}}/edit" class="btn btn-success float-left mr-2">Edit</a>
                                    <form action="{{ route('patients.destroy', $patient->id)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit" onclick="return confirm(`Are you sure you want to delete city '{{ $patient->name }}'?`);">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
    </tbody>
  </table>
        {{$patients->links()}}
    @else
        <p>No patient found</p>
    @endif
    <div>
</div>
@endsection

resources/views/patients/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-4 mb-2">
        <div class="col-sm-6 offset-sm-2">
            <h1>Patient Information</h1>
        </div>
        <div class="col-sm-2">
            <a href="/patients" class="btn btn-success pull-right float-right">Go back</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <table class="table table-striped">
                <tr>
                    <th>Name</th>
                    <th>Barangay</th>
                    <th>City</th>
                    <th>Number</th>
                    <th>Email</th>
                    <th>Case Type</th>
                    <th>Corona Virus Status</th>
                </tr>
                <tr>
                    <td>{{ $patient->name }}</td>
                    <td>{{ $barangay->name }}</td>
                    <td>{{ $city->name }}</td>
                    <td>{{ $patient->number }}</td>
                    <td>{{ $patient->email !== null ? $patient->email : "N/A" }}</td>
                    <td>{{ $patient->case_type }}</td>
                    @if ($patient->case_type === "Positive")
                        <td>{{ $patient->coronavirus_status }}</td>
                    @endif
            </table>
        </div>
    </div>
@endsection