routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cities', 'CityController');
Route::resource('barangays', 'BarangayController');
Route::resource('patients', 'PatientController');
Route::get('/patient-checkstatus', 'CheckStatusController@index');
Route::get('/awareness-report', 'AwarenessReportsController@index');
Route::get('/coronavirus-report', 'CoronaVirusReportsController@index');

app/Barangay.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Barangay extends Model
{
    // The attributes that are mass assignable
    protected $fillable = [
        'name',
        'city_id'     
    ];

    // Relationship city to barangays
    public function city(){
        return $this->belongsTo(City::class);
    }

    // Relationship many patients to one barangay
    public function patients(){
        return $this->HasMany(Patient::class);
    }
}

app/Http/Controllers/BarangayController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Barangay;
use App\City;

class BarangayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    /** Authentication for pages **/
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    } 

    public function index()
    {
        /**  Retrieve all barangays **/
        $barangays = Barangay::orderBy('name', 'asc')->paginate(10);
        $cities = City::all();
        return view('barangays.index')->with(['barangays' => $barangays, 'cities' => $cities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /**  Create new barangay **/
        $cities = City::all();
        return view('barangays.create')->with(['cities' => $cities]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /** Form Validation **/
        $this->validate($request, [
            'name' => 'required',
            'city' => 'required'
        ]);

        /** Create Barangay **/
        $barangay = new Barangay;
        $barangay->name = $request->input('name');
        $barangay->city_id = $request->input('city');
        $barangay->save();

        return redirect('/barangays')->with('success', 'Barangay Saved!.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /**  Show barangay information **/
        $barangays = Barangay::find($id);
        $city = Barangay::find($id)->city;
        return view('barangays.show')->with(['barangays' => $barangays, 'city' => $city]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        /**  Edit city **/
        $barangays = Barangay::find($id);
        $cities = City::all();
        return view('barangays.edit')->with(['barangays' => $barangays, 'cities' => $cities]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**  Form validation **/ 
        $this->validate($request, [
            'name' => 'required',
            'city' => 'required'
        ]);

        /**  Update barangay information **/
        $barangay = Barangay::find($id);
        $barangay->name = $request->input('name');
        $barangay->city_id = $request->input('city');
        $barangay->save();
        return redirect('/barangays')->with('success', 'Barangay Upated!.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        /**  Delete a barangay **/
        $barangay = Barangay::find($id);
        $barangay->delete();
        return redirect('/barangays')->with('success', 'Barangay deleted!');
    }
}

resources/views/barangays/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row mt-5">
 <div class="col-sm-8 offset-sm-2">
    <h1>Add a Barangay</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('barangays.store') }}">
          @csrf
          <div class="form-group ">    
              <label for="first_name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>   
        <div class="form-group ">
                    <label for="city">City</label>
                    <select class="form-control" id="city" name="city">
                        <option value="">Select City</option>
                        @foreach ($cities as $city)
                            <option value="{{ $city->id }}">{{ $city->name }}</option>
                        @endforeach
                    </select>
        </div>  
          <button type="submit" class="btn btn-warning">Add</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/barangays/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row mt-4 mb-2">
        <div class="col-sm-8 offset-sm-2">
            <h1>Update Barangay</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="/barangays/{{ $barangays->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name <span class="required">*</span></label>
                    <input type="text" name="name" value="{{ $barangays->name }}" class="form-control" id="name" placeholder="Enter name of brgy">
                </div>
                <div class="form-group">
                    <label for="city">City <span class="required">*</span></label>
                    <select class="form-control" id="city" name="city">
                        <option value="">--Select City--</option>
                        @foreach ($cities as $city)
                            @if ($barangays->city_id == $city->id)
                                <option value="{{ $city->id }}" selected="selected">{{ $city->name }}</option>
                            @else
                                <option value="{{ $city->id }}">{{ $city->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Update</button> <a href="/barangays" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
@endsection

resources/views/barangays/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
<div class="col-sm-8 offset-sm-2">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
<div class="row mt-4 mb-2">
<div class="col-sm-8 offset-sm-2">
    <div class="row">
        <div class="col-sm-6">
            <h1>Barangay</h1>
        </div>
        <div class="col-sm-6">
            <a href="/barangays/create" class="btn btn-warning pull-right float-right">Add Barangay</a>
        </div>
    </div>
    @if(count($barangays) > 0)
        <table class="table table-striped">
    <thead>
        <tr>
          <th>Name</th>
          <th>City</th>
          <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($barangays as $barangay)
        <tr>
            <td>{{$barangay->name}}</td>
            @foreach ($cities as $city)
                @if ($city->id == $barangay->city_id)
                    <td>{{$city->name}}</td>
                @endif
            @endforeach
            <td>
                    <a href="barangays/{{$barangay->id}}" class="btn btn-primary float-left mr-2">View</a>
                    <a href="/barangays/{{$barangay->id}}/edit" class="btn btn-success float-left mr-2"><i class="fa fa-edit"></i>Edit</a>
                    <form action="/barangays/{{ $barangay->id }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                    <input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm(`Are you sure you want to delete barangay '{{ $barangay->name }}'?`);">
                    </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
        {{$barangays->links()}}
    @else
        <p>No barangay found</p>
    @endif
    <div>
</div>
@endsection

resources/views/barangays/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-4 mb-2">
        <div class="col-sm-6 offset-sm-2">
            <h1 >Barangay Information</h1>
        </div>
        <div class="col-sm-2">
            <a href="/barangays" class="btn btn-success pull-right float-right">Go back</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <table class="table table-striped">
                <tr>
                    <th>Barangay</th>
                    <th>City</th>
                    
                </tr>
                <tr>
                    <td>{{ $barangays->name }}</td>
                    <td>{{ $city->name }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection